spring:
  profiles:
    # system config (local, dev, prod)
    active: local
  application:
    name: '${spring.profiles.active}-application-name'

  # mail
  # mail:
  #   host: smtp.gmail.com
  #   port: 587
  #   username: 931csl@gmail.com
  #   password: 1q2w3e4r!@#
  #   properties:
  #     mail:
  #       smtp:
  #         auth: true
  #         starttls:
  #           enable: true

  # # OAuth2
  # security:
  #   oauth2:
  #     client:
  #       registration:
  #         google:
  #           client-id: your-google-client-id
  #           client-secret: your-google-client-secret
  #           redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
  #           scope:
  #             - email
  #             - profile

  # DB
  datasource:
    # driver-class-name: org.postgresql.Driver
    # url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost:5432/sample
    username: postgres
    password: 1q2w3e4r!@#
    hikari:
      maximum-pool-size: 4

mybatis:
  mapper-locations: classpath:mybatis/mapper/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl # mybatis preparing, parameters 로그 제외
    map-underscore-to-camel-case: true

# server
server:
  port: 8080
  servlet:
    encoding:
      force-response: true
      charset: UTF-8

# slf4j
logging:
  pattern:
    console: "%highlight([%-5level] [%d{yyyy-MM-dd HH:mm:ss.SSS}] [%c{0}]:%-3L - %msg%n)"
    file   : "%highlight([%-5level] [%d{yyyy-MM-dd HH:mm:ss.SSS}] [%c] [%M] [%-3L] - %msg%n)"
    rolling-file-name: "/logs/log.%d{yyyy-MM-dd}.%i"

  file:
    name: /logs/log.log
    max-history: 300

  level:
    root: DEBUG
    com.sample.backend: DEBUG
    jdbc:
      connection: ERROR
      resultset: ERROR
      audit: ERROR
      sqlonly: ERROR
      sqltiming: ERROR
      resultsettable: DEBUG

    org.springframework:
        boot: INFO
        web: INFO
        beans: INFO
    com.zaxxer: ERROR
    org.postgresql: ERROR
    org.springframework.jdbc: ERROR
    org.mybatis.spring: ERROR
    org.apache.tomcat.util: INFO
    org.apache.catalina.core: INFO
    org.apache.poi: INFO

environment:
  AES_KEY: Hf6hvV2pJAmleFyoxcm62A==
  message:
    path: src/main/resources/i18n
    name_rule: /message_{0}.json
  fileUpload: C://Users/dev/Desktop/workspace/upload/